2025-03-19 07:46:18 - WARNING: {'<pad>': 0, '<suc>': 1, 'monomer': 2, 'organic': 3, 'inorganic': 4, 'condition': 5, 'polymer_family': 6, 'syn_method': 7, 'prop_name': 8, 'prop_value': 9, 'ref_exp': 10, 'char_method': 11, 'polymer': 12, 'material_amount': 13, 'composite': 14, 'other_material': 15}
2025-03-19 07:46:18 - INFO: Building Model
2025-03-19 07:46:18 - WARNING: 2025-03-19 07:46:18 - INFO: Building Model
2025-03-19 07:46:24 - ERROR: Task dev_tasks.process_pdf_task[9aa9fa73-0f52-406d-9859-4f1f060fd538] raised unexpected: RuntimeError('Error(s) in loading state_dict for Model:\n\tUnexpected key(s) in state_dict: "bert.embeddings.position_ids". ')
Traceback (most recent call last):
  File "/home/antrieu/miniconda3/envs/mineru/lib/python3.10/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/antrieu/miniconda3/envs/mineru/lib/python3.10/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/antrieu/drive/RIKEN/dev_tasks.py", line 109, in process_pdf_task
    ner_model, ner_logger, ner_config = load_ner_model()
  File "/home/antrieu/drive/RIKEN/NER/main_predict.py", line 80, in load_ner_model
    model.load_state_dict(torch.load(config.save_path))
  File "/home/antrieu/miniconda3/envs/mineru/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "bert.embeddings.position_ids". 
2025-03-19 07:46:24 - WARNING: 2025-03-19 07:46:24 - ERROR: Task dev_tasks.process_pdf_task[9aa9fa73-0f52-406d-9859-4f1f060fd538] raised unexpected: RuntimeError('Error(s) in loading state_dict for Model:\n\tUnexpected key(s) in state_dict: "bert.embeddings.position_ids". ')
Traceback (most recent call last):
  File "/home/antrieu/miniconda3/envs/mineru/lib/python3.10/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/antrieu/miniconda3/envs/mineru/lib/python3.10/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/antrieu/drive/RIKEN/dev_tasks.py", line 109, in process_pdf_task
    ner_model, ner_logger, ner_config = load_ner_model()
  File "/home/antrieu/drive/RIKEN/NER/main_predict.py", line 80, in load_ner_model
    model.load_state_dict(torch.load(config.save_path))
  File "/home/antrieu/miniconda3/envs/mineru/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "bert.embeddings.position_ids". 
